# shift_time: The amount of time in seconds between shifts. 60 <= shift_time <= (2^32)-1
# countdown: Length of the countdown before the game starts in seconds. 0 will cancel the countdown altogether.
# warn_time: How long the countdown will go for before players are shifted.
# warn_half: Dictates whether players will be notified at half-time between shifts.
# random_teleport: Indicates whether you want players to be teleported to random players each shift or not.
# know_next_target: Dictates whether players will be informed who they are teleporting to on shift.
# random_initial_teleport: Dictates whether players will be teleported to a random position on game start.
#
shift_time: 300
countdown: 5
warn_time: 10
warn_half: false
random_teleport: false
know_next_target: true
random_initial_teleport: true
portals_enabled: true
